
### Education

|  |  |
|:------------------------------------------------------|----------------:|
| **PhD in Ecophysiology** at the Thechnical University of Denmark <br> With the project “Growth and metabolic scaling of fish: unravelling how variation in growth affects metabolic scaling” with Tommy Norin | 2022--2025 |
| **Masters in Ecophysiology**, Aarhus University <br> Master’s thesis: “Measuring and inhibiting protein synthesis in European Perch	(*Perca fluviatilis*)” with Mark Bayley, section of Zoophysiology | 2019--2021 |
| **Bachelors in Biology**, Aarhus University <br> Bachelor’s thesis: “The effect of different stress levels on mean arterial pressure (MAP) and heart rate (HR) in Ball python (*Python regius*)” with Tobias Wang, Section of zoophysiology  | 2016--2019 |
| **Highshool**, Risskov Gymnasium <br> Part of youth science talet program "Science Talenter" during all 3 years and participated in the finale of young scinetist | 2012--2015 |
| **Student exchange** in Australia | 2011--2012 |

### Work expirience

|  |  |
|:------------------------------------------------------|----------------:|
| **Research assistant**, at Christopher Topping, professor, Department of Ecoscience - 	Biodiversity and Conservation, Aarhus University | 2021--2022 |
| **Private highschool tourtor** | 2020--2022 |
| **Student helper**, Student helper at Simon Skov, Senior adviser, Department of Geosciences and	Natural Resource Management - Forest, Nature and Biomass, Copenhagen University | 2018--2021 |
| **Mailman**, at PostNord | 2015--2017 |
| **Chef's assistance**, at RealMat, Oslo | 2012 |

### Volentier work

|  |  |
|:------------------------------------------------------|----------------:|
| **Member of PhD committee**, at DTU Aqua | 2023--2024 |
| **Chairman of the bord**, at Børglum kollegiet | 2020--2021 |
| **Tenant committee member**,at Børglum kollegiet | 2019--2022 |
| **Scout leader**, at 1.Risskov Drenge DDS  | 2018--2022 |
| **Assistant scout leader**, at 1.Risskov Drenge DDS  | 2013--2018 |

### Supervision

**MSc students**

|  |  |
|:------------------------------------------------------|----------------:|
| Julius Wilborg Exsteen, University of Copenhagen. Co-supervisor for project: *Metabolic scaling and growth within individual guppies: testing the gill-oxygen limitation theory* | 2024 |
| Axel Frederik Moesby, University of Copenhagen. Co-supervisor for project: *Effect of early-life temperature variation on the scaling of metabolic and growth rates of rainbow trout* | 2023 |
| Petur Mikkelsen, Thechnical University of Denmark. Co-supervisor for project: *Round goby in an increasingly hypoxic world: Determination of its critical oxygen level* | 2023 |
| Emilie Winther Engelsbak, Thechnical University of Denmark. Co-supervisor for project: *Interactive effects of multiple stressors on blue mussel physiology in a warming Arctic* | 2023 |


### Teaching

|  |  |
|:------------------------------------------------------|----------------:|
| *Oceanography*. Teaching assistant and supervisior for group doing respirometry on round gobys. | 2023-- 2025|
| *Experimental marine biology*. Teaching assistant.  | 2024 |
| *Ecology*.  Teaching assistant | 2023 |

### Grants

|  |  |
|:------------------------------------------------------|----------------:|
| **SEB Conference Travel Grant**, granted to attend the annual meeting in Prag, France (300 GBP) | 2023 |
| **The Company of Biologists Traveling Fellowship**, granted to do fieldwork in French Polynesia, France (3000 GBP) | 2023 |
| **Otto Mønsted foundation**, granted to do fieldwork in French Polynesia, France (20 000 DKK) | 2023 |
| **Friday harbor internal funding**, granted to attend 5 week coerce at Friday Harbor laboratories on San Juan island, USA (2081 USD) | 2023 |
| **The Company of Biologists Travel Grant**, granted by the Society for Experimental Biology to attend the annual meeting in Montpellier, France (500 GBP) | 2022 |

### Fieldwork experience

|  |  |
|:------------------------------------------------------|----------------:|
| **Copepod collection and measurements**, at the Artic station, Disko Island, Greenland (1 month) | 2025 |
| **Monitoring, catching and measuring on free living coral fish**, at the CRIOBE, French Polynesia, France (4 month) | 2024 |
| **Beach Seining and fish sorting**, at the Friday Harbor laboratories, San Juan island, USA (1 month) | 2023 |
