### Key skils

|  |
|:-----------------------------------------------------------------------|
| **Languge** <br> Danish (native languge), English (fluent), Norwegian (fluent) and German (basic) |
| **Data processing and statistical analyis** <br> • Handling and processing large data sheets <br> • Data manipulation, statistical analyses and data visualisation in R <br> • Developed comprehensive reproducible R scripts for processing and analysis of raw data <br> • Image analysis of lens sizes in birds and measuring body condition in whales using ImageJ <br> • Working with old fisheries data from logbooks and interviews|
| **Laboratory** <br> • Fish husbandry both in long term populations in a laboratory and short term in field stations <br> • Fish reproduction, anaesthesia and euthanasia  <br> • Measuring metabolic rates in organism ranging from moderately sized fish to copepods and mitochondria <br> • Measuring maximum metabolic rate in fish using  techniques such as swim tunnels and chase protocols <br> • Measuring both O~2~ use, and CO~2~ production simultaneously in fish <br> • Manipulating hypoxia and hyperoxia during respirometry <br> • Tagging with visible elastomer and implanted tags (PIT tags)  <br> • Fish experimentation (IP injections and dissections) <br> • Measuring rates of protein synthesis using Puromycin, Western blotting and fluorescence protein labeling <br> • Pharmaceuticaly inhibiting protein synthesis using Rapamycin and Cycloheximide <br> • Video tracking of fish behaviour  <br> • Building experimental setups in both state of the art laboratories and in remote field locations <br> • Counting fish eggs under a microscope <br> • Snake surgery (cannulation)|
| **Field** <br> • Monitoring fish populations on coral reefs <br> • Transept surveys both terrestrial and marine <br> • Non lethal ways of catching live fish sush as beach seining and underwater using scuba and hand nets|
| **Administrative** <br> • Reporting and organising data into standardised national reporting frameworks  <br> • Invoice handling and budgeting <br> • Planing and leading projects of different sizes <br> • Writing post project reports for relevant authorities |

### Licences

|  |  |
|:--------------------------------------------------|--------------------:|
| **Driving licence**, Danish category AM/B <br> **Moterboat licence**, Danish <br> **Diving licence**, PADI Advanced Open Water <br> **Animal experimental licence**, Danish category B |  |
